### ISSUE TITLE
Missing matching table between citation network and article IDs

### ISSUE THREAD

**Issue by msantolini** [mattbierbaum/arxiv-public-datasets#1]
Hi and thanks for the valuable ressource!
I notice that the ID used in internal-references-v0.2.0-2019-03-01.json (such as "alg-geom/9509005") is different than the one  used in arxiv-metadata-hash-abstracts-v0.2.0-2019-03-01.json (such as "704.0002"). Do you have a matching table allowing to go from one to the other?
Thanks!

**Comment by colinclement** [comment]
Hi Marc,

Thanks for your interest! There are two kinds of arxiv IDs, ones like
"alg-geom/9509005"
were the standard before 2007, and ones like "704.0002" are now the
standard. Therefore both types should exist in both datasets. Something
else that you'll probably want to know is that there are missing PDFs on
the arxiv (there are 1.39 million PDFs but 1.5 million articles total).
Since we use the PDFs to extract the citation network, there will be
missing nodes in the graph for which metadata exists.

I don't think we yet link to the arxiv paper accompanying this repository,
so this https://arxiv.org/abs/1905.00075 will probably be helpful in
understanding more of the idiosyncrasies of the arxiv.

Please let us know if anything else doesn't make sense or isn't working!

Best,
Colin

**Comment by mattbierbaum** [comment]
I updated the readme to include the link to the article (fixed on c684114).

**Comment by msantolini** [comment]
Thanks for the very useful answer!
