### ISSUE TITLE
out of memory in fulltext.convert_directory_parallel()

### ISSUE THREAD

**Issue by quynhneo** [mattbierbaum/arxiv-public-datasets#15]
For the full set of PDFs, which is now 2.3TB and 2.2 millions files, https://github.com/mattbierbaum/arxiv-public-datasets/blob/8b2e49fde5a1be13c777638d5f60cf0f5e0ae759/arxiv_public_data/fulltext.py#L270 will run out of memory (tested for 2GB, and 4GB). Should we free the memory frequently? for example adding 
`gc.collect() `
to https://github.com/mattbierbaum/arxiv-public-datasets/blob/8b2e49fde5a1be13c777638d5f60cf0f5e0ae759/arxiv_public_data/fulltext.py#L306
Each pdf file is only ~1MB, nothing should gradually occupy RAM that much.

**Comment by colinclement** [comment]
Did you test the garbage collection and find that it fixed the issue for you? Since the PDF conversion is executed in a subprocess `gc.collect()` will not be able to see and free up reference counts from the python-based PDF conversion. Part of the issue could be that some PDFs take an extraordinarily long time, and so to keep the pipeline from being paralyzed we put a time limit on conversion, re-trying the time-limited PDFs with another conversion tool. The time limit may kill the subprocess and leave some memory unfreed. You can try adding `maxtasksperchild=1` to [the multiprocessing Pool initialization](https://github.com/mattbierbaum/arxiv-public-datasets/blob/8b2e49fde5a1be13c777638d5f60cf0f5e0ae759/arxiv_public_data/fulltext.py#L292), so that if there is memory leaking from the underlying conversion, that will be freed up by always re-initializing a subprocess for each job. We did not find memory leaking issues when we ran this ourselves, though we also ran on a machine with 1TB of memory, so the issue may not have been a deal-breaker.

If the `maxtasksperchild` modification fixes it for you, consider submitting a PR.

**Comment by quynhneo** [comment]
I did not try gc.collect() but it worked after I delete temporary files (https://github.com/mattbierbaum/arxiv-public-datasets/pull/14)
