### ISSUE TITLE
Downloading PDFs in JSON/XML format

### ISSUE THREAD

**Issue by arghyadeep99** [mattbierbaum/arxiv-public-datasets#17]
Is there any way to download the PDFs in JSON/XML format, to ensure the structure remains when using it for any machine learning task, where separation of sections may become necessary? Looking forward to some solutions. Thank you!

**Comment by colinclement** [comment]
There is `pdftohtml` which you can [install in ubuntu](http://manpages.ubuntu.com/manpages/bionic/man1/pdftohtml.1.html) and which can convert PDFs into XML or HTML. You can probably just replace this tool in our pipeline wherever `pdf2text` is used. There is also [`pdfalto`](https://github.com/kermitt2/pdfalto). No one tool will work for all documents, there will always be tradeoffs. In our pipeline we use a few PDF to text tools as sometimes one fails or hangs, for example.

**Comment by colinclement** [comment]
Hi @arghyadeep99, please advise whether your issue is resolved by my suggestion. If so, feel free to close this issue.

**Comment by arghyadeep99** [comment]
Yes, thanks. I will close the issue.

**Comment by kermitt2** [comment]
Hello! For arXiv articles, [GROBID](https://github.com/kermitt2/grobid) should be used rather than pdfalto. pdfalto is just a preprocessing at layout level without information loss, it does not structure (it's like `PDF.js` or `pdftohtml`). 
GROBID will structure the document and generate an XML version for text mining, for building a citation network, for matching affiliation, etc. 
As mentioned, GROBID is a tradeoff, but it works quite well with arXiv papers if the motivation is then text mining, you can test the online demo.

**Comment by colinclement** [comment]
Thanks for the suggestion, @kermitt2. Please feel free to submit a PR enabling the use of GROBID in the pipeline.
