### ISSUE TITLE
WinError2: System can not find the file

### ISSUE THREAD

**Issue by dxhura** [mattbierbaum/arxiv-public-datasets#18]
Hello together! This is more of a beginner question but still wondering if someone could help! I downloaded a small portion of the ArXiv data set under my_path\tarpdfs\. When trying to convert the PDFs to text, although the files are there and get listed I get a  [WinError 2] System can not find the given file, error. Would you have any hints on how to solve it?
![image](https://user-images.githubusercontent.com/8044928/131733829-4bd9e391-ce78-4e50-ac02-234ffb0303f6.png)

**Comment by colinclement** [comment]
Hi @dxhura! I'm sorry but we've never tested these tools in Windows. I suspect it's because we use a subprocess call in Python to a bash command which uses a tool which does not exist in Windows. You could try installing it, but the subprocess commands are written for nix. I recommend [installing the WSL](https://docs.microsoft.com/en-us/windows/wsl/install) (windows subsystem for linux).

**Comment by RichardScottOZ** [comment]
Or you could download unix-utils and get those to work, be easier, if just a simple thing from there

**Comment by colinclement** [comment]
I can't guarantee all of the subprocess calls we make are POSIX-compliant, so I believe WSL would be easier in that it will almost surely work. @dxhura feel free to close the issue if your issue is resolved.

**Comment by colinclement** [comment]
@dxhura I will close this issue as it's been about six months, and so I will assume it's resolved. Please feel free to re-open the issue if I am mistaken.
