### ISSUE TITLE
Is it possiable to provide a link to download fulltext

### ISSUE THREAD

**Issue by wabyking** [mattbierbaum/arxiv-public-datasets#7]
The reason is that I do not have enough space to download all pdfs (more than  1T) but also want to use full text (70G), which is manageable,

**Comment by colinclement** [comment]
Unfortunately, due to the copyright license of arXiv papers, the arXiv has exclusive rights to distribute the papers. You could modify our pipeline slightly, only downloading one of the ~2000 tarpdf dumps and processing it, and then deleted the tarpdf. In this way you would not have to store it all on disk. You could do so by modifying [this script](https://github.com/mattbierbaum/arxiv-public-datasets/blob/master/bin/pdfdownload.py), passing into `s3_bulk_download.download_check_tarfiles` only one part of the manifest (still a list) at a time. And then you can make the same modification to [this script](https://github.com/mattbierbaum/arxiv-public-datasets/blob/master/bin/fulltext.py) to convert the PDFs contained in that one manifest file to fulltext.

**Comment by wabyking** [comment]
thanks a lot for your kind reply
